---
title: "The Next Generation of Canadian Salmon"
subtitle: "The Effects of the Commercial Fishing Industry on Spawning Rates"
author: 
  - Timothius Prajogi
thanks: "Code and data are available at: https://github.com/prajogt/canadian_salmon_spawn.git ."
date: today
date-format: long
abstract: "Using the NuSEDS dataset and Catch Estimates for the Pacific Region Commerical Salmon Fishery dataset provided by the Government of Canada, we investigate the effects of commercial fishing on the reproductive capacity of Canadian Salmon. Along with that, we investigate how much of the change in spawn rates can be attributed to the health of the ecosystem, climate, and the fish that live in it. This paper discusses the impact of direct human intervention in the form of commercial fishing, aiming to highlight the importance in proper management and control in the fishing industry in alignement with changes in the environment by predicting spawning trends of future generations."
format: pdf
toc: true
number-sections: true
bibliography: references.bib
header-includes:
  \usepackage{placeins}
---

# Introduction

The declining trend in Canadian salmon runs, as observed by many avid anglers and supported by empirical data (INSERT CITATION), serves as the focal point of this paper. Once thriving waterways have experienced a significant reduction in salmon populations, posing challenges not only for recreational anglers but also for the fishing industry, a vital component of Canadian exports and numerous livelihoods, particularly in coastal regions. Due to this significance to many Canadians, it is important to investigate the decline in salmon runs, highlighting the importance of understanding and addressing these challenges that are faced in the effort to safeguard future salmon generations.

This paper will focus on commercial fishing trends, ocean climate trends, and spawning rates over the last decade, using datasets and fisheries statistics provided through the Government of Canada's open data portal. In particular, the NuSEDS (New Salmon Escapement Database System) provides key insights on spawner records and abundance estimates for freshwater streams and tributaries, with statistics provided by Fisheries and Oceans Canada providing detail on the amount of fish landed or released by species. Through this data we discover the potential human-induced drivers of salmon population change including factors such as over fishing and artificial breeding. In identifying the critical areas for repair and reform, we aim to explore potential mitigation strategies and management plans with the goal of restoring salmon populations and promoting sustainable fishing practices, protecting this key resource. Preserving healthy salmon populations is not only essential for maintaining biodiversity and ecosystem balance but also for meeting demand required of this industry, both in labour and in product. 

Through information gathered from these datasets, we were able to verify correlations between the frequency of fishing and the salmon population, as well as the previous years salmon population and artificial breeding practices affect on future generations. However, although these are significant factors, they do not account for all the change that is seen throughout the years. Salmon population's fluctuation cannot be fully explained by these human factors alone, which means there must be some other factors that are not described in this data that should be investigated. 

This paper will introduce the data and models we used to analyze these themes and trends, explaining why features and datasets were chosen and how they are relevant to the research topic. Then the paper will present our findings and their implications for future salmon generations observed in the models that were created as well as in the data. We will conclude by discussing the weaknesses and future steps that could be made to further improve on this research.

# Data

# Model

# Results

# Discussion

# Appendix

# References

